spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Project
    password: 12345
    username: postgres
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      base-path: C:\Users\Asus\IdeaProjects\Project\src\main\resources\static
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 8640000000 # a day
      refresh-token:
        expiration: 6048000000 # 7 days

