spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Project
    password: 12345
    username: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      base-path: C:\Users\Asus\IdeaProjects\Project\src\main\resources\static

